server:
  port: 8081

# todo :: move to application-test.yml
#spring:
#  datasource:
#    url: jdbc:h2:mem:demo
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console.enabled: true

application:
  config:
    dir: "${CONFIGURATION:/opt/configuration}"
management:
  endpoints:
    web:
      base-path: /