spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/passage-db
    username: admin
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update